### ISSUE TITLE
Load surveys issue triggered by hard back button Android 

### ISSUE THREAD

**Issue by dianaplesa** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS#5] opened 2017-10-26 11:39 UTC
When you're in the middle of completing a survey and you press back button from Android, the survey is closed. If you try to access the same survey after you closed it using back button, without completing it, either the didSurveyCompleted method is called and you can no longer access that survey until after you uninstall the app, or the survey is opened to the last question, not the first question from survey or the last question that it was closed as normal. 

Do you have any recommendations to solve this problem? Is there something we can do in our code or it is a bug that comes from you?

**Comment by dinesh-opg** [comment] 2017-10-26 13:02
We just want to know which opgsdk version you are using ?
We have fixed an issue related to back button in our latest opgsdklitev1.5.So better use that.

This is in accordance with opgsdklitev1.5.

**When you're in the middle of completing a survey and you press back button from Android, the survey is closed.**
Here there are 2 possibilities
I)If you are passing the panelID and panellistId in the loadOnlineSurvey method then the survey will be resumed from where you stopped before clicking backbutton.
II)If you aren't passing the panelID and panellistId in the loadOnlineSurvey .Then everytime it will start with first question.

**If you try to access the same survey after you closed it using back button, without completing it, either the didSurveyCompleted method is called and you can no longer access that survey until after you uninstall the app,**

We are not clear with this point so can please elobrate on this more.

**Do you have any recommendations to solve this problem?**
We recommend to disable the back button when the survey question is loading.Or you also can use a progress bar dialog which has inderterminate as true and cancelable set false. and use this progress dialog in the OPGSurveyInterface callback methods

Check the below example for better understanding
[click here]([TakeSurveyActivity.txt](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/files/1418400/TakeSurveyActivity.txt))

**Comment by dianaplesa** [comment] 2017-10-27 13:06
We are using opgsdk_lite_v1.5 and we have only begun to meet these issues since we upgraded to this version. 

We have implemented an activity very similar to yours and we are passing the panelID and panellistID in the loadOnlineSurvey method.

However, not every we got through the specified flow, but quite often, we encounter these problems. Sometimes it happens that the survey is open to the first question and not the one we stopped before pressing the back button.

PanelID and panellistID are sent correctly as it appears from exported data from the OPG platform.

**If you try to access the same survey after you closed it using back button, without completing it, either the didSurveyCompleted method is called and you can no longer access that survey until after you uninstall the app.**

Normally, when a question from a survey is opened, didSurveyStartLoad and didSurveyFinishLoad methods are called in this order and when a survey is completed, didSurveyCompleted method is called. Sometimes, when you close a survey without completing it and then you go back and try to access it again, only didSurveyCompleted method is called, without didSurveyStartLoad or didSurveyFinishLoad and you can not access that survey anymore. Only if you uninstall the app and install it again.

**Comment by dinesh-opg** [comment] 2017-10-27 13:34
Hi Dianaplesa,

 We will check into the above mentioned issue and notify you on this asap.

**Comment by dinesh-opg** [comment] 2017-10-30 07:43
Hi Dianaplesa,

Can you please mention which opgsdk method you are using for the getting the list of surveys.

**Comment by dianaplesa** [comment] 2017-10-30 10:28
Hello,

We are using getSurveyList() method for getting the list of surveys.

**Comment by dinesh-opg** [comment] 2017-10-30 11:31
getSurveyList() :- This method returns the list of surveys based on admin username and shared key. This method will give the list of surveys (OPGSurvey) without authentication.

getUserSurveyList() :- This method returns only the list of surveys assigned to a particular panellist.This method can be accessed only after successfull authentication.

As you are using the getSurveyList() method you will get the surveys not assigned to the panellist.And hence their previous instances is not stored .Only the surveys assigned to the panellist can restore their previous state(i.e resuming from last closed question.)
So please use the getUserSurveyList() method for restoring the survey previous state.

**Comment by dianaplesa** [comment] 2017-10-31 10:49
I get an empty list when I use this method. I only send the context as a parameter to this method, just as I did when using getSurveyList().

Is there something I'm doing wrong?

**Comment by dinesh-opg** [comment] 2017-10-31 10:55
You need to get the authentication done for using this getUserSurveyList().
Please check this url
[click here](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/wiki/03.-How-to-get-surveys-using-panellist-authentication%3F).
If you still don't get the survey list it means that no survey is assigned to the panellist.So please add your email and create a panellist and assign the surveys to it.

**Comment by dianaplesa** [comment] 2017-10-31 12:18
I logged out and logged in again and it's working now, I can see my list of surveys. 

Even so, I still encounter the above mentioned issue sometimes when trying to restore the survey previous state.

**Comment by dinesh-opg** [comment] 2017-10-31 12:25
Restoring issue will not happening if we follow the above mentioned [process](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/wiki/03.-How-to-get-surveys-using-panellist-authentication%3F).
Only if you don't pass valid panelID and panellistID to loadOnlineSurvey you will get that restore issue.So please check you are passing valid panelID and panellistID.

**Comment by dianaplesa** [comment] 2017-10-31 12:49
The panelID and panellistID I pass to loadOnlineSurvey method are valid. I just checked them.

This is the activity I am using for taking the surveys [TakeSurveyActivity.pdf](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/files/1430738/TakeSurveyActivity.pdf)

**Comment by dianaplesa** [comment] 2017-10-31 15:04
I'm not able to open this file. Can you please try to send it again?

**Comment by dinesh-opg** [comment] 2017-10-31 15:57
[modifiedTakeSurveyActivity.txt](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/files/1431345/modifiedTakeSurveyActivity.txt)
Please find the file attached

**Comment by dianaplesa** [comment] 2017-11-01 08:46
Still not working.

**Comment by dianaplesa** [comment] 2017-11-01 09:00
However, I have noticed that one of the surveys (out of 8) is working as expected. It's the first survey from our list and it has a different design from the others. 

Could be influenced by the implementation of the surveys in any way?

**Comment by NeerajOPG** [comment] 2017-11-02 08:14
**However, I have noticed that one of the surveys (out of 8) is working as expected. It's the first survey from our list and it has a different design from the others.**
It is good that it is working for one survey.There may be possibility that for other surveys it was not able to get the correct panelId or panellistId.

**Could be influenced by the implementation of the surveys in any way?**
No, It could not be influenced by the implementation of surveys.

**We suggest you to check our DemoApp. Please  test that your surveys are working fine or not in DemoApp.**

We have created the DemoApp to demonstrtate the sdk.
[Download ](http://apidev.1pt.mobi/apps/android/DemoApp/DemoApp_Version_1.0.apk)  and install it. 
**Steps to take survey in DemoApp.**
1. Open the DemoApp
2. Click on "Authenticate"  in the list, authenticate your self by entering the fields(Admin name, Admin SharedKey, panellistUserName, panellistPassword, appVersion).
   Then click on "AUTHENTICATE" button if authentication is successfull you will get uniqeId and success message.
3. Click on "1.SurveyList" in the list  and click "submit" button,it will load all the surveys.
   However if you want to load the survey for particular panel then enter panelId and check that checkBox and click "submit" button. it will load the surveys which are in that panel.
4. Click on any listed survey to run it.

You can also check the [source code](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/tree/Development/DemoSurveysAndroid) of the DemoApp

please let me know if anything else is needed.

**Comment by dianaplesa** [comment] 2017-11-02 10:10
We just tested your DemoApp and it works just like in our application.

Do you think it would help if we could send you our surveys? Would help you identify the problem more easily?

**Comment by NeerajOPG** [comment] 2017-11-02 12:34
As we are able to reproduce the issue in one scenario that is **one survey is assigned to two panels** so **getPanelID()** method of **BrowseActivity**.java is not returning **same panelID** every time because inside getPanelID() we are calling 
`OPGPanellistPanel opgPanellistPanel = Util.getOPGSDKInstance().getPanellistPanel(mContext);
 List<OPGSurveyPanel> opgSurveyPanels = opgPanellistPanel.getSurveyPanelArray();` 
which return an List of OPGSurveyPanel objcet and the order of objects in the list is not sorted.  So every it returns the panelId of OPGSurveyPanel object which comes first in the list.

So we recommend you to not to call the getPanellistPanel() sdk method every time instead of it you can save the list of  OPGSurveyPanel in your local SQLite db or SharedPreference. 

I have updated the code and new build of [DemoApp](http://apidev.1pt.mobi/apps/android/DemoApp/DemoApp_Version_1.1.apk). please test again.
In this i am saving the OPGPanellistPanel  object in local variable in **Util.java**
I am saving the list in local variable so the app will work fine until you kill it.
 Please check that also.

**Comment by dianaplesa** [comment] 2017-11-02 12:59
Now, it turns me back to the first question every time I close the survey.

**Comment by dinesh-opg** [comment] 2017-11-03 12:35
Hi @dianaplesa  we will check into this and get back to you.

**Comment by dougmorris** [comment] 2017-11-06 12:18
Hi @dianaplesa we can see a potential issue with the running of the script and are investigating further to assess how it can be resolved.

**Comment by dianaplesa** [comment] 2017-11-07 08:37
Ok, thank you @dougmorris. We're waiting for your answer.

**Comment by dougmorris** [comment] 2017-11-07 14:28
The bug has been identified and fixed. for survey scripts that include pages where the same info type question is used more than once throughout the survey the survey engine assumed that the question had already been answered which lead to the survey effectively being reset to the first question each time. the survey engine has been modified to stop this happening in the future. Please confirm that your survey is running as expected now.

**Comment by dianaplesa** [comment] 2017-11-08 10:19
Thank you. We have tested the surveys and they are working as expected.

We tested using the activity I sent you above and it's working fine, without any changes.

**Comment by onepoint** [comment] 2019-10-09 11:15
Closed

**Closed by onepoint** 2019-10-09 11:15 UTC
